Module10 commet pub sub
ArtsiomMusin/thinknetica-pro-rails pull request #10
Opened 2016-09-16 09:04 UTC by ArtsiomMusin

2016-09-16 09:55 UTC, vkurennov commented on thinknetica_qna/app/controllers/concerns/commented.rb
> +module Commented
Комментарий - это отдельный ресурс, да, он зависит от вопроса или овтета, но это не их составная часть. Консерны нужно не везде применять. Здесь нужен отдельный вложенный контроллера для комментариев.

2016-09-16 09:57 UTC, vkurennov commented on thinknetica_qna/app/views/answers/_answers.html.slim
> += subscribe_to "/comments/answer"
У тебя канал для комментариев к ответу один (и это правильно), но ты подписываешься на него для каждого ответа. Т.е. когда ты выводишь их список, то каждый раз вызывается эта команда и подписывает на один и тот же канал. А достаточно сделать это всего один раз

2016-09-16 09:58 UTC, vkurennov commented on thinknetica_qna/app/views/questions/_question.html.slim
> += subscribe_to "/comments/question"
И тут опять будет подписка несколько раз, если выводить вопросы в цикле

2016-09-16 09:58 UTC, vkurennov requested changes
Исправь замечания

2016-09-16 11:59 UTC, ArtsiomMusin commented on thinknetica_qna/app/controllers/concerns/commented.rb
> +module Commented
эх, ясно, да тут я думал как лучше, в начале был контроллер, но потом подумал, что консерн лучше...

2016-09-16 12:34 UTC, vkurennov commented on thinknetica_qna/app/controllers/comments_controller.rb
> +          PrivatePub.publish_to "/comments/#{@commentable.class.to_s.downcase}", comment: @comment.to_json
Т.к. у тебя нет привязки к странице (например, по id вопроса), то все пользователи получат данные в канал. Но отобразатся они только у тех, кто находится на нужной странице. Так зачем слать данные всем, если они нужны только части клиентов?

2016-09-16 12:35 UTC, vkurennov commented on thinknetica_qna/app/controllers/comments_controller.rb
> +    if @comment
А зачем тут эта проверка? Используй @commentable.comments.build и у тебя гарантировано будет здесь объект

2016-09-16 12:36 UTC, vkurennov commented on thinknetica_qna/app/controllers/comments_controller.rb
> +     if params[:question_id]
Тут надо хитрее сделать: через регулярку вытащить первую часть адреса (между слешами) и через нее уже получить класс и id. Немного метапрограммирования. Погугли по фразе "polymorphic rails controller"

2016-09-16 12:38 UTC, vkurennov requested changes
Исправь замечания

2016-09-16 19:49 UTC, ArtsiomMusin commented on thinknetica_qna/app/controllers/comments_controller.rb
> +    if @comment
да, она не нужна, убрал

2016-09-16 19:49 UTC, ArtsiomMusin commented on thinknetica_qna/app/controllers/comments_controller.rb
> +          PrivatePub.publish_to "/comments/#{@commentable.class.to_s.downcase}", comment: @comment.to_json
не сразу понял о чем идет речь, но вроде понял. Переделал так, что теперь завязка по айди на каждый вопрос/ответ. Может не лучшее решение по производительность, а может и норм. Я тут не знаю, но сейчас точно не кидаем данные в общий канал. :sunglasses:

2016-09-16 19:49 UTC, ArtsiomMusin commented on thinknetica_qna/app/controllers/comments_controller.rb
> +     if params[:question_id]
про регулярку я думал, но не знал, что можно достать сам адрес. Подправил

2016-09-16 20:24 UTC, vkurennov commented on thinknetica_qna/app/controllers/comments_controller.rb
> +        PrivatePub.publish_to "/#{@commentable.class.to_s.downcase}s/#{@commentable.id}/comments", comment: @comment.to_json
В таком случае у тебя создаются каналы на каждый ответ и на сам вопрос, это слишко нагружает браузер. проще создать 1 канал вида `questions/:id/comments`, а уже на клиенте определять к чему этот комент.

2016-09-16 20:25 UTC, vkurennov requested changes
Надеюсь, последнее замечание

2016-09-16 21:57 UTC, ArtsiomMusin commented on thinknetica_qna/app/controllers/comments_controller.rb
> +        PrivatePub.publish_to "/#{@commentable.class.to_s.downcase}s/#{@commentable.id}/comments", comment: @comment.to_json
ясно, поменял на один канал для ответа с вопросами

2016-09-17 09:27 UTC, vkurennov commented on thinknetica_qna/app/models/answer.rb
> +  def channel_name
Зачем метод в модели-то? Разве сложно было прописать в контроллере название канала ну или метод для определения названия канала там же? Модель вообще-то ничего не должна знать о деталях отображения, это дело контроллера и вида.

2016-09-17 09:27 UTC, vkurennov commented on thinknetica_qna/app/models/concerns/commentable.rb
> +  def build_comment(params)
А зачем тебе этот метод? Чем comments.build не устраивает?

2016-09-17 09:28 UTC, vkurennov commented on thinknetica_qna/app/models/question.rb
> +  def channel_name
Вот это в контроллере должно быть

2016-09-17 09:28 UTC, vkurennov approved these changes
Принимаю, но исправь замечания при выполнении след. задания

2016-09-17 18:08 UTC, ArtsiomMusin commented on thinknetica_qna/app/models/answer.rb
> +  def channel_name
В модели потому, что самый красивый вариант. В контроллере даже метапрограммирование не поможет и надо делать типа
```
  def channel_name
     if @commentable.instance_of? Question
       id = @commentable.id
     elsif @commentable.instance_of? Answer
       id = @commentable.question.id
     end
     "questions/#{id}/comments"
   end
```
получаются спагетти из if'ов когда несколько объектов передаем в этот контреллер. 
А через модели выглядит гораздо лучше хоть и нелогично.

2016-09-17 18:08 UTC, ArtsiomMusin commented on thinknetica_qna/app/models/concerns/commentable.rb
> +  def build_comment(params)
все в модель перенес даже такие мелочи :smile:

2016-09-18 08:33 UTC, merged