Module13 authorization in rails
ArtsiomMusin/thinknetica-pro-rails pull request #13
Opened 2016-09-23 21:01 UTC by ArtsiomMusin

2016-09-24 07:52 UTC, vkurennov commented on thinknetica_qna/app/controllers/application_controller.rb
> +    redirect_to root_url, :alert => exception.message
У тебя есть несколько типов запросов - html, js, json, последние 2 - это ajax-запросы, в которых нет смысла делать редирект, т.к. юзер не увидит его (он же в фоне). Поэтому надо сделать обработчик для разных форматов: 
 - для html  - редирект
 - для js - общая вьюха, кторая ставит флеш-сообщение на страницу и возвращает 403 статус
 - для json - сообщение в json и статус 403 + обработчик на странице, который это сообщение показывает юзеру.

2016-09-24 07:52 UTC, vkurennov commented on thinknetica_qna/app/models/ability.rb
> +    can [:update, :destroy], [Question, Answer], user: user
Сравнивай по user_id, чтобы не делать лишний запрос к базе

2016-09-24 07:53 UTC, vkurennov commented on thinknetica_qna/app/models/ability.rb
> +    can :mark_best, Answer, user: user
И тут user_id

2016-09-24 07:53 UTC, vkurennov requested changes
Исправь замечания

2016-09-24 20:16 UTC, ArtsiomMusin commented on thinknetica_qna/app/controllers/application_controller.rb
> +    redirect_to root_url, :alert => exception.message
Добавил все форматы

2016-09-25 07:52 UTC, vkurennov commented on thinknetica_qna/app/controllers/application_controller.rb
> +      format.json { render json: { errors: [exception.message] }, status: :forbidden }
Верно, только я не увидел обработчика этого варианта на клиенте. Надо сделать глобальный обработчик для всего документа. Можно в нем фильтровать по статусу, например, если статус 403, то показываем сообщение, в остальных случаях, ничего не делаем.

2016-09-25 07:53 UTC, vkurennov commented on thinknetica_qna/app/models/ability.rb
> +      subject.user_id == user.id
Можно было и без блока: `can [:update, :destroy], [Question, Answer], user_id: user.id`. user_id - это же атрибут модели

2016-09-25 07:54 UTC, vkurennov commented on thinknetica_qna/app/models/ability.rb
> +      subject.user_id == user.id
А если уж блок используешь, тогда лучше метод `author_of?` использовать везде

2016-09-25 07:54 UTC, vkurennov approved these changes
Принято, но исправь замечания перед выполнением следующего задания

2016-09-25 20:35 UTC, ArtsiomMusin commented on thinknetica_qna/app/controllers/application_controller.rb
> +      format.json { render json: { errors: [exception.message] }, status: :forbidden }
по сути уже все обработчики были и он работали нормально(кроме одного для комментариев, где я подправил, чтобы работало), но я добавил и глобальный обработчик

2016-09-25 20:36 UTC, ArtsiomMusin commented on thinknetica_qna/app/models/ability.rb
> +      subject.user_id == user.id
Исправил на `author_of?`

2016-09-25 20:36 UTC, merged