Module15 rest api part2
ArtsiomMusin/thinknetica-pro-rails pull request #15
Opened 2016-09-28 23:15 UTC by ArtsiomMusin

2016-09-29 13:11 UTC, vkurennov requested changes
Исправь замечания

2016-09-29 13:11 UTC, vkurennov commented on thinknetica_qna/app/controllers/api/v1/answers_controller.rb
> +    respond_with Question.find(params[:question_id]).answers
Все же лучше загружать родительский объект в переменную, это болегчает чтение кода

2016-09-29 13:11 UTC, vkurennov commented on thinknetica_qna/app/controllers/api/v1/answers_controller.rb
> +    question = Question.find(params[:question_id])
А тут уже дублирование, лучше вынести в метод и повесить в before_action

2016-09-29 13:11 UTC, vkurennov commented on thinknetica_qna/app/controllers/api/v1/answers_controller.rb
> +class Api::V1::AnswersController < Api::V1::BaseController
Что-то не вижу авторизации в контроллере

2016-09-29 13:11 UTC, vkurennov commented on thinknetica_qna/app/controllers/api/v1/answers_controller.rb
> +    question = Question.find(params[:question_id])
А тут уже дублирование, лучше вынести в метод и повесить в before_action

2016-09-29 13:11 UTC, vkurennov commented on thinknetica_qna/app/controllers/api/v1/profiles_controller.rb
> +class Api::V1::ProfilesController < Api::V1::BaseController
Добавь авторизацию

2016-09-29 13:11 UTC, vkurennov commented on thinknetica_qna/app/controllers/api/v1/questions_controller.rb
> +class Api::V1::QuestionsController < Api::V1::BaseController
Добавь авторизацию

2016-09-29 13:11 UTC, vkurennov commented on thinknetica_qna/spec/api/v1/answers_spec.rb
> +      it 'creates a new answer with parameters' do
А также надо еще проверить, что ответ связывается с вопросом и залогиненным пользователем (current_resiurce_owner)

2016-09-29 13:11 UTC, vkurennov commented on thinknetica_qna/spec/api/v1/questions_spec.rb
> +        expect { post '/api/v1/questions', params: { format: :json, access_token: access_token.token, question: attributes_for(:question) } }.to change(Question, :count).by(1)
А тут надо проверить, что вопрос связывается с юезром от имени которого совершен запрос

2016-09-29 14:06 UTC, ArtsiomMusin commented on thinknetica_qna/app/controllers/api/v1/answers_controller.rb
> +class Api::V1::AnswersController < Api::V1::BaseController
ну она ж в бейс контроллере вынесена
```
class Api::V1::BaseController < ApplicationController
  before_action :doorkeeper_authorize!

```

2016-09-29 14:06 UTC, ArtsiomMusin commented on thinknetica_qna/app/controllers/api/v1/answers_controller.rb
> +    respond_with Question.find(params[:question_id]).answers
ок, подправил

2016-09-29 14:22 UTC, ArtsiomMusin commented on thinknetica_qna/spec/api/v1/answers_spec.rb
> +      it 'creates a new answer with parameters' do
Добавил тест на проверку юзера

2016-09-29 14:22 UTC, ArtsiomMusin commented on thinknetica_qna/spec/api/v1/questions_spec.rb
> +        expect { post '/api/v1/questions', params: { format: :json, access_token: access_token.token, question: attributes_for(:question) } }.to change(Question, :count).by(1)
Тоже добавил один тест

2016-09-29 14:22 UTC, ArtsiomMusin commented on thinknetica_qna/app/controllers/api/v1/answers_controller.rb
> +    question = Question.find(params[:question_id])
Убрал дублирование

2016-09-30 09:13 UTC, vkurennov requested changes
Нужно добавить авторизацию через cancan

2016-09-30 09:13 UTC, vkurennov commented on thinknetica_qna/app/controllers/api/v1/answers_controller.rb
> +class Api::V1::AnswersController < Api::V1::BaseController
Это не авторизация, а аутентификация. Пусть название тебя не смущает. Т.е. определение что за юзер сделал запрос. А авторизация - это проверка прав пользователя. Или в API мы права не проверяем? Добавь CanCan, короче.

2016-09-30 11:26 UTC, ArtsiomMusin commented
Авторизация/аутентицикация... :dizzy_face: Надо запомнить кто есть кто.
Добавил сancan

2016-09-30 16:15 UTC, vkurennov approved these changes
Принято, но исправь замечания

2016-09-30 16:15 UTC, vkurennov commented on thinknetica_qna/app/controllers/application_controller.rb
> +    return User.find(doorkeeper_token.resource_owner_id) if doorkeeper_token
Я бы тут использвал тоже мемоизацию, т.к. метод может несколько раз вызываться в рамках одного запроса и в случае с API каждый раз будет запрос к базе.

2016-10-02 18:54 UTC, merged