Module17 background jobs
ArtsiomMusin/thinknetica-pro-rails pull request #17
Opened 2016-10-08 00:09 UTC by ArtsiomMusin

2016-10-08 11:30 UTC, vkurennov requested changes
Похоже, под конец курса ты расслабился, что сразу же отразилось на качестве кода. Исправь замечания

2016-10-08 11:30 UTC, vkurennov commented on thinknetica_qna/app/controllers/questions_controller.rb
> +  after_action :publish_question, :subscribe_author, only: :create
Это должно быть не в контроллере, а в коллбеках модели. Т.к. неважно, как мы создаем вопрос, автора надо подписать. Иначе, нужно дублировать код еще и в API

2016-10-08 11:30 UTC, vkurennov commented on thinknetica_qna/app/models/answer.rb
> +    AnswerMailer.digest(self.question.user).deliver_later
А зачем автора уведомлять отдельно, если он в подписчиках? Он же дважды письмо получит тогда

2016-10-08 11:30 UTC, vkurennov commented on thinknetica_qna/app/models/subscriber.rb
> +  belongs_to :question
А belongs_to :user чего не сделал?

2016-10-08 11:30 UTC, vkurennov commented on thinknetica_qna/app/models/subscriber.rb
> +class Subscriber < ApplicationRecord
Правильнее назвать модель Subscription -  подписка, потому что Subscriber - это тот же юзер. И можно сделать ассоциацию в Question под названием subscribers, но класс у них будет User.

2016-10-08 11:30 UTC, vkurennov commented on thinknetica_qna/app/models/user.rb
> +    entity.subscribers.each do |subscriber|
Ну приехали. Под конец курс делать подсчет и выборки средствами руби, это конечно сильно. Давай нормальный запрос через ARel сделай. Там делов-то, посмотреть, есть ли в таблице подписок запись с заданным user_id и question_id

2016-10-08 11:30 UTC, vkurennov commented on thinknetica_qna/app/views/subscribers/destroy.js.erb
> +<% if @subscriber.errors.present? %>
А что,  при удалении могут быть ошибки валидаиции?

2016-10-08 11:30 UTC, vkurennov commented on thinknetica_qna/db/migrate/20161006200101_create_subscribers.rb
> +      t.integer :user_id
У тебя поиск по этому полю идет, нужно индекс добавить

2016-10-08 11:30 UTC, vkurennov commented on thinknetica_qna/spec/models/answer_spec.rb
> +    it 'sends an email to the question author' do
А проверка, что всем подписичкам высылается письмо?

2016-10-08 11:30 UTC, vkurennov commented on thinknetica_qna/spec/models/question_spec.rb
> +  context '#extract_subscriber' do
Название метода, конечно, неудачное, как и модели Subscriber.

2016-10-08 14:49 UTC, ArtsiomMusin commented on thinknetica_qna/app/controllers/questions_controller.rb
> +  after_action :publish_question, :subscribe_author, only: :create
ok, исправлено

2016-10-08 14:49 UTC, ArtsiomMusin commented on thinknetica_qna/app/models/answer.rb
> +    AnswerMailer.digest(self.question.user).deliver_later
Изначально я только уведомлял автора, а потом добавил уведомления для всех подписчиков. И видимо забыл, что это повторение получается. Убрал.

2016-10-08 14:49 UTC, ArtsiomMusin commented on thinknetica_qna/app/models/subscriber.rb
> +class Subscriber < ApplicationRecord
Переименовал в Subscription

2016-10-08 14:50 UTC, ArtsiomMusin commented on thinknetica_qna/app/models/subscriber.rb
> +  belongs_to :question
просто добавил поле с user_id, а то какое-то мессиво из ассоциаций получается. Думал про это в начале, но решил сделать проще. Или все равно лучше делать через ассоциации?

2016-10-08 14:50 UTC, ArtsiomMusin commented on thinknetica_qna/app/models/user.rb
> +    entity.subscribers.each do |subscriber|
Была ночь, мозг по немного отказывался думать... :laughing: Исправил

2016-10-08 14:50 UTC, ArtsiomMusin commented on thinknetica_qna/app/views/subscribers/destroy.js.erb
> +<% if @subscriber.errors.present? %>
нет, убрал и добавил ! для destroy

2016-10-08 14:50 UTC, ArtsiomMusin commented on thinknetica_qna/db/migrate/20161006200101_create_subscribers.rb
> +      t.integer :user_id
Добавил

2016-10-08 14:50 UTC, ArtsiomMusin commented on thinknetica_qna/spec/models/answer_spec.rb
> +    it 'sends an email to the question author' do
Добавил

2016-10-08 14:50 UTC, ArtsiomMusin commented on thinknetica_qna/spec/models/question_spec.rb
> +  context '#extract_subscriber' do
изменил

2016-10-08 19:00 UTC, vkurennov commented on thinknetica_qna/app/models/subscriber.rb
> +  belongs_to :question
Конечно лучеш через ассоциации, все равно ты с user_id работаешь как с ассоциацией и фактически это она и есть

2016-10-08 19:08 UTC, vkurennov requested changes
Гораздо лучше, но можно еще лучше сделать

2016-10-08 19:08 UTC, vkurennov commented on thinknetica_qna/app/models/answer.rb
> +      user = User.find(subscription.user_id)
А зачем find, если теперь есть ассоциация? Можно же вызывать `subscription.user`. А еще лучше - сделать ассоциацию subscribers в модели Question через `has_many through`, тогда можно будет обращаться сразу к подписчикам: `question.subscribers`

2016-10-08 19:08 UTC, vkurennov commented on thinknetica_qna/app/models/question.rb
> +  has_many :subscriptions, dependent: :destroy
А еще добавь has_many through для подписчиков (subscribers) и обращайся к подписчикам вопроса через эту ассоциацию

2016-10-08 19:08 UTC, vkurennov commented on thinknetica_qna/app/models/question.rb
> +  scope :daily_created, ->() { where('created_at >= ?', Time.now - 1.day) }
Тут надо не от текущего времени отталкиваться, т.к. задача же не ровно минута в минуту запускается каждый раз, может быть некий лаг и в итоге не все вопросы попадут в выборку. Сделай так, чтобы были вопросы только за вчерашний день (с 0 до 24 ч предыдущей даты).

2016-10-08 19:08 UTC, vkurennov commented on thinknetica_qna/app/models/subscription.rb
> +  belongs_to :question
Добавь все же ассоциацию на user, ведь фактически, это она и есть

2016-10-08 19:08 UTC, vkurennov commented on thinknetica_qna/spec/models/answer_spec.rb
> +      question.subscriptions = []
Зачем? Это же ассоциация.

2016-10-08 21:10 UTC, ArtsiomMusin commented on thinknetica_qna/app/models/answer.rb
> +      user = User.find(subscription.user_id)
да с ассоциацией уже find не нужен. 
В начале нифига не понял как тут добавить subscribers, но вроде в доках нашел и добавил.

2016-10-08 21:11 UTC, ArtsiomMusin commented on thinknetica_qna/app/models/question.rb
> +  has_many :subscriptions, dependent: :destroy
Добавил

2016-10-08 21:11 UTC, ArtsiomMusin commented on thinknetica_qna/app/models/question.rb
> +  scope :daily_created, ->() { where('created_at >= ?', Time.now - 1.day) }
сделал через range от начала до конца вчерашнего дня.

2016-10-08 21:11 UTC, ArtsiomMusin commented on thinknetica_qna/app/models/subscription.rb
> +  belongs_to :question
Добавил

2016-10-08 21:11 UTC, ArtsiomMusin commented on thinknetica_qna/spec/models/answer_spec.rb
> +      question.subscriptions = []
Суть была в том, что я проверял только подписчиков без автора. Так как ассоциация это технически массив, этим присвоением я убирал лишнего(для этого теста только) автора из подписчиков. 

Но я переделал спеку, чтобы и автор тоже проверялся.

2016-10-09 09:28 UTC, vkurennov approved these changes
Принято

2016-10-10 09:55 UTC, merged